<script lang="ts">
	import { onMount } from 'svelte';
	import { resolve } from '$app/paths';

	onMount(() => {
		// Scroll to top when page loads
		window.scrollTo(0, 0);
	});
</script>

<svelte:head>
	<title>Privacy Policy - Journey To Mordor</title>
	<meta
		name="description"
		content="Privacy policy for Journey To Mordor - Learn how we handle your data"
	/>
</svelte:head>

<div class="mx-auto max-w-3xl space-y-6 rounded-lg bg-white p-8 shadow-md">
	<div class="border-b border-slate-200 pb-4">
		<h1 class="font-serif text-5xl font-normal text-slate-800">Privacy Policy</h1>
		<p class="mt-2 text-sm text-slate-500">Last updated: January 26, 2026</p>
	</div>

	<section class="space-y-4">
		<h2 class="font-serif text-3xl font-normal text-slate-800">Overview</h2>
		<p class="text-slate-700">
			Journey To Mordor is designed with your privacy in mind. We believe you should have full
			control over your data, which is why we've built this application to work entirely without an
			account if you prefer.
		</p>
	</section>

	<section class="space-y-4">
		<h2 class="font-serif text-3xl font-normal text-slate-800">Data Controller</h2>
		<p class="text-slate-700">
			For the purposes of the General Data Protection Regulation (GDPR), the data controller for
			this application is the individual or entity operating this instance of Journey To Mordor.
			When you use Firebase authentication and cloud storage features, Google LLC acts as a data
			processor on behalf of the data controller.
		</p>
	</section>

	<section class="space-y-4">
		<h2 class="font-serif text-3xl font-normal text-slate-800">Data Storage Options</h2>

		<div class="space-y-6">
			<div class="rounded-lg border-l-4 border-shire-500 bg-shire-50 p-4">
				<h3 class="mb-2 font-semibold text-shire-900">Without Login (Default)</h3>
				<ul class="list-disc space-y-2 pl-5 text-shire-800">
					<li>All your journey data is stored locally in your browser's local storage</li>
					<li>No data is sent to our servers or any third-party services</li>
					<li>Your data remains on your device only</li>
					<li>
						If you clear your browser data or use a different device, your progress will not be
						available
					</li>
					<li>No account creation or personal information required</li>
				</ul>
			</div>

			<div class="rounded-lg border-l-4 border-ring-500 bg-ring-50 p-4">
				<h3 class="mb-2 font-semibold text-ring-900">With Login (Optional)</h3>
				<ul class="list-disc space-y-2 pl-5 text-ring-800">
					<li>Your journey data is backed up to Firebase Cloud Firestore</li>
					<li>You can access your progress from any device by logging in</li>
					<li>Your data automatically syncs between devices</li>
					<li>
						We store: your journey logs (date, distance, optional notes), and your unit preference
						(km/miles)
					</li>
					<li>
						Authentication is handled by Firebase Authentication using your chosen provider (Google,
						Facebook, Microsoft, Apple, or Email)
					</li>
				</ul>
			</div>
		</div>
	</section>

	<section class="space-y-4">
		<h2 class="font-serif text-3xl font-normal text-slate-800">Legal Basis for Processing</h2>
		<p class="text-slate-700">
			Under GDPR, we process your personal data based on the following legal grounds:
		</p>
		<ul class="list-disc space-y-2 pl-5 text-slate-700">
			<li>
				<strong>Consent:</strong> When you choose to create an account and log in, you provide explicit
				consent for us to process your authentication and journey data
			</li>
			<li>
				<strong>Contract:</strong> Processing is necessary to provide the cloud sync service you have
				requested
			</li>
			<li>
				<strong>Legitimate Interest:</strong> We have a legitimate interest in providing and improving
				our service
			</li>
		</ul>
	</section>

	<section class="space-y-4">
		<h2 class="font-serif text-3xl font-normal text-slate-800">
			Information We Collect (When Logged In)
		</h2>
		<div class="space-y-3 text-slate-700">
			<div>
				<h3 class="font-semibold text-slate-800">Authentication Information:</h3>
				<ul class="list-disc pl-5">
					<li>Email address (if using email authentication)</li>
					<li>Display name and profile photo (from OAuth providers)</li>
					<li>Unique user identifier (generated by Firebase)</li>
				</ul>
			</div>
			<div>
				<h3 class="font-semibold text-slate-800">Journey Data:</h3>
				<ul class="list-disc pl-5">
					<li>Activity log entries (date, distance, optional notes)</li>
					<li>Unit preference (kilometers or miles)</li>
				</ul>
			</div>
			<p class="text-sm italic">
				We do not collect any other personal data such as your IP address, device information, or
				browsing behavior.
			</p>
		</div>
	</section>

	<section class="space-y-4">
		<h2 class="font-serif text-3xl font-normal text-slate-800">How We Use Your Data</h2>
		<p class="text-slate-700">When you choose to log in, we use your data solely to:</p>
		<ul class="list-disc space-y-2 pl-5 text-slate-700">
			<li>Store and sync your journey progress across devices</li>
			<li>Authenticate your identity when you sign in</li>
			<li>Display your progress and statistics</li>
		</ul>
		<p class="text-slate-700">
			We <strong>do not</strong> use your data for:
		</p>
		<ul class="list-disc space-y-2 pl-5 text-slate-700">
			<li>Advertising or marketing purposes</li>
			<li>Analytics or tracking</li>
			<li>Profiling or automated decision-making</li>
			<li>Sharing with third parties (except as required service providers like Firebase)</li>
		</ul>
	</section>

	<section class="space-y-4">
		<h2 class="font-serif text-3xl font-normal text-slate-800">Data Retention</h2>
		<p class="text-slate-700">
			We retain your data for as long as your account is active or as needed to provide you with our
			services. You can request deletion of your data at any time by using the
			<!-- eslint-disable svelte/no-navigation-without-resolve -->
			<a
				href={resolve('/my-data') + '#delete-account'}
				class="font-semibold text-ring-600 hover:underline"
			>
				"Delete Account"
			</a>
			feature, which will permanently remove all your data from our systems within 30 days.
		</p>
	</section>

	<section class="space-y-4">
		<h2 class="font-serif text-3xl font-normal text-slate-800">Data Sharing and Transfers</h2>
		<p class="text-slate-700">
			We do not sell, trade, or rent your personal data to third parties. Your data is only shared
			with:
		</p>
		<ul class="list-disc space-y-2 pl-5 text-slate-700">
			<li>
				<strong>Firebase (Google LLC):</strong> As our cloud infrastructure provider, Firebase processes
				your data on our behalf as a data processor
			</li>
			<li>
				<strong>OAuth Providers:</strong> When you choose to sign in with Google, Facebook, Microsoft,
				or Apple, minimal authentication data is shared with these providers
			</li>
		</ul>
		<p class="text-slate-700">
			Your data may be transferred to and processed in countries outside the European Economic Area
			(EEA). Firebase is certified under the EU-U.S. Data Privacy Framework and employs appropriate
			safeguards to ensure GDPR compliance.
		</p>
	</section>

	<section class="space-y-4">
		<h2 class="font-serif text-3xl font-normal text-slate-800">Third-Party Services</h2>
		<div class="space-y-4 text-slate-700">
			<div class="rounded-lg border border-slate-200 bg-slate-50 p-4">
				<h3 class="mb-2 font-semibold text-slate-800">Firebase (Google LLC)</h3>
				<p class="mb-2">
					We use Firebase for authentication and cloud storage. Firebase is GDPR-compliant and acts
					as a data processor. Key privacy features include:
				</p>
				<ul class="list-disc space-y-1 pl-5 text-sm">
					<li>Data encryption in transit (HTTPS) and at rest</li>
					<li>Logical isolation of customer data</li>
					<li>Restricted employee access with 2-factor authentication</li>
					<li>Compliance with major privacy and security standards</li>
					<li>Data Processing and Security Terms that detail GDPR responsibilities</li>
				</ul>
				<p class="mt-2 text-sm">
					Full privacy policy:
					<a
						href="https://firebase.google.com/support/privacy"
						target="_blank"
						rel="noopener noreferrer"
						class="text-ring-600 hover:underline"
					>
						firebase.google.com/support/privacy
					</a>
				</p>
			</div>

			<div class="rounded-lg border border-slate-200 bg-slate-50 p-4">
				<h3 class="mb-2 font-semibold text-slate-800">OAuth Authentication Providers</h3>
				<p class="mb-2">
					When you sign in with Google, Facebook, Microsoft, or Apple, these providers handle the
					authentication process. In practice, this means:
				</p>
				<ul class="list-disc space-y-1 pl-5 text-sm">
					<li>
						You are redirected to the provider's login page (e.g., accounts.google.com for Google)
					</li>
					<li>The provider authenticates you and may log this login event in their systems</li>
					<li>
						The provider may collect metadata such as your IP address, device type, and login
						timestamp
					</li>
					<li>
						The provider shares only basic profile information with us (name, email, profile photo)
					</li>
					<li>
						The provider may use this information according to their own privacy policies for
						security, analytics, or service improvement
					</li>
				</ul>
				<p class="mt-2 text-sm">
					We recommend reviewing the privacy policies of your chosen authentication provider:
				</p>
				<ul class="mt-1 list-disc space-y-1 pl-5 text-sm">
					<li>
						Google:
						<a
							href="https://policies.google.com/privacy"
							target="_blank"
							rel="noopener noreferrer"
							class="text-ring-600 hover:underline">policies.google.com/privacy</a
						>
					</li>
					<li>
						Facebook:
						<a
							href="https://www.facebook.com/privacy/policy"
							target="_blank"
							rel="noopener noreferrer"
							class="text-ring-600 hover:underline">facebook.com/privacy/policy</a
						>
					</li>
					<li>
						Microsoft:
						<a
							href="https://privacy.microsoft.com/privacystatement"
							target="_blank"
							rel="noopener noreferrer"
							class="text-ring-600 hover:underline">privacy.microsoft.com/privacystatement</a
						>
					</li>
					<li>
						Apple:
						<a
							href="https://www.apple.com/legal/privacy/"
							target="_blank"
							rel="noopener noreferrer"
							class="text-ring-600 hover:underline">apple.com/legal/privacy</a
						>
					</li>
				</ul>
			</div>
		</div>
	</section>

	<section class="space-y-4">
		<h2 class="font-serif text-3xl font-normal text-slate-800">Data Security</h2>
		<p class="text-slate-700">
			We implement appropriate technical and organizational measures to protect your personal data
			against unauthorized access, alteration, disclosure, or destruction:
		</p>
		<ul class="list-disc space-y-2 pl-5 text-slate-700">
			<li>Data encryption in transit using HTTPS</li>
			<li>Data encryption at rest in Firebase Cloud Firestore</li>
			<li>Secure authentication via Firebase Authentication</li>
			<li>Regular security updates and monitoring</li>
		</ul>
		<p class="text-slate-700">
			However, no method of transmission over the internet is 100% secure, and we cannot guarantee
			absolute security. You are responsible for maintaining the confidentiality of your account
			credentials.
		</p>
	</section>

	<section class="space-y-4">
		<h2 class="font-serif text-3xl font-normal text-slate-800">Your Rights Under GDPR</h2>
		<p class="text-slate-700">
			If you are in the European Economic Area (EEA), you have the following rights regarding your
			personal data:
		</p>
		<ul class="list-disc space-y-2 pl-5 text-slate-700">
			<li>
				<strong>Right of Access:</strong> You can view all your journey data within the application at
				any time
			</li>
			<li>
				<strong>Right to Rectification:</strong> You can edit or correct your journey entries at any time
			</li>
			<li>
				<strong>Right to Erasure ("Right to be Forgotten"):</strong> You can delete individual entries,
				all your data, or your entire account using the in-app features
			</li>
			<li>
				<strong>Right to Data Portability:</strong> You can export your journey logs in JSON format from
				the "Log Journey" tab
			</li>
			<li>
				<strong>Right to Withdraw Consent:</strong> You can stop using the cloud sync feature by deleting
				your account or simply using the app without logging in
			</li>
			<li>
				<strong>Right to Object:</strong> You can object to data processing by not creating an account
				or by deleting your existing account
			</li>
			<li>
				<strong>Right to Lodge a Complaint:</strong> You have the right to lodge a complaint with your
				local data protection authority
			</li>
		</ul>
		<p class="text-slate-700">
			To exercise these rights, you can use the in-app features or contact us through the channels
			listed below.
		</p>
		<div class="mt-4 rounded-lg border border-ring-200 bg-ring-50 p-4">
			<p class="text-sm text-ring-900">
				<strong>💡 Tip:</strong> Visit our
				<a
					href={resolve('/my-data')}
					class="font-semibold text-ring-700 underline hover:text-ring-800">My Data</a
				>
				page to view all your stored data, export it, or delete your account.
			</p>
		</div>
	</section>

	<section class="space-y-4">
		<h2 class="font-serif text-3xl font-normal text-slate-800">Children's Privacy</h2>
		<p class="text-slate-700">
			This application is not directed to children under 16 (or the applicable age of digital
			consent in your jurisdiction). We do not knowingly collect personal information from children.
			If you are a parent or guardian and believe we have collected information from a child, please
			contact us immediately, and we will delete such information.
		</p>
	</section>

	<section class="space-y-4">
		<h2 class="font-serif text-3xl font-normal text-slate-800">Changes to This Policy</h2>
		<p class="text-slate-700">
			We may update this privacy policy from time to time to reflect changes in our practices or for
			legal, operational, or regulatory reasons. We will notify you of any material changes by
			updating the "Last updated" date at the top of this policy. We encourage you to review this
			policy periodically. Your continued use of the application after any changes indicates your
			acceptance of the updated policy.
		</p>
	</section>

	<section class="space-y-4">
		<h2 class="font-serif text-3xl font-normal text-slate-800">Contact</h2>
		<p class="text-slate-700">
			If you have any questions about this privacy policy, your data, or wish to exercise your GDPR
			rights, please contact us through the GitHub repository for this project:
		</p>
		<ul class="mt-3 space-y-2 text-slate-700">
			<li>
				<strong>For general questions:</strong>
				<a
					href="https://github.com/hakkelt/JourneyToMordor/discussions"
					target="_blank"
					rel="noopener noreferrer"
					class="text-ring-600 hover:underline"
				>
					GitHub Discussions
				</a>
			</li>
			<li>
				<strong>For privacy concerns or data requests:</strong>
				<a
					href="https://github.com/hakkelt/JourneyToMordor/issues"
					target="_blank"
					rel="noopener noreferrer"
					class="text-ring-600 hover:underline"
				>
					GitHub Issues
				</a>
			</li>
		</ul>
		<p class="mt-3 text-sm text-slate-600">
			Repository:
			<a
				href="https://github.com/hakkelt/JourneyToMordor"
				target="_blank"
				rel="noopener noreferrer"
				class="text-ring-600 hover:underline"
			>
				github.com/hakkelt/JourneyToMordor
			</a>
		</p>
	</section>

	<div class="mt-8 border-t border-slate-200 pt-6 text-center">
		<a
			href={resolve('/')}
			class="inline-block rounded-lg bg-ring-600 px-6 py-3 font-semibold text-white transition hover:bg-ring-700"
		>
			← Back to Journey
		</a>
	</div>
</div>
