import { defineConfig } from 'vitest/config';
import tailwindcss from '@tailwindcss/vite';
import { sveltekit } from '@sveltejs/kit/vite';
import { enhancedImages } from '@sveltejs/enhanced-img';
import { VitePWA } from 'vite-plugin-pwa';

// A revision token that changes with every build. Prerendered HTML pages do
// not contain a content hash in their URL, so workbox cannot detect whether
// their content has changed. Using a build-time timestamp ensures the service
// worker re-fetches them on every new deployment (harmless because a new SW
// is deployed anyway whenever any hashed JS/CSS asset changes).
const buildRevision = Date.now().toString();

export default defineConfig({
	plugins: [
		enhancedImages(),
		tailwindcss(),
		sveltekit(),
		VitePWA({
			registerType: 'autoUpdate',
			devOptions: {
				enabled: true,
				type: 'module'
			},
			injectRegister: 'inline',
			workbox: {
				// globPatterns covers JS/CSS/HTML/icon bundles produced by Vite.
				// Image assets (webp, avif, png) are intentionally excluded here:
				// warmImageCache() detects browser format support (avif/webp/png) at
				// runtime and fetches only the appropriate variant, which the CacheFirst
				// runtime handler below then persists for offline use. Precaching all
				// image variants would download redundant formats (both avif and webp)
				// on every SW installation, overriding this smart format selection.
				globPatterns: ['**/*.{js,css,html,ico,svg,json}'],
				cleanupOutdatedCaches: true,
				maximumFileSizeToCacheInBytes: 5 * 1024 * 1024, // 5 MiB
				// Prerendered HTML pages are generated by the SvelteKit adapter
				// after the Vite build, so they are not found by globPatterns.
				// They must be listed here with a build-specific revision so that
				// the service worker re-caches them on every new deployment.
				// Keep this list in sync with the prerendered routes in src/routes/.
				additionalManifestEntries: [
					{ url: 'index.html', revision: buildRevision },
					{ url: 'logs.html', revision: buildRevision },
					{ url: 'my-data.html', revision: buildRevision },
					{ url: 'credits.html', revision: buildRevision },
					{ url: 'privacy.html', revision: buildRevision }
				],
				runtimeCaching: [
					{
						urlPattern: /\.(?:png|jpg|jpeg|webp|avif|gif)$/i,
						handler: 'CacheFirst',
						options: {
							cacheName: 'images',
							expiration: {
								maxEntries: 100,
								maxAgeSeconds: 30 * 24 * 60 * 60 // 30 Days
							}
						}
					},
					{
						urlPattern: /^https:\/\/fonts\.googleapis\.com\/.*/i,
						handler: 'CacheFirst',
						options: {
							cacheName: 'google-fonts-cache',
							expiration: {
								maxEntries: 10,
								maxAgeSeconds: 60 * 60 * 24 * 365 // 365 days
							},
							cacheableResponse: {
								statuses: [0, 200]
							}
						}
					},
					{
						urlPattern: /^https:\/\/fonts\.gstatic\.com\/.*/i,
						handler: 'CacheFirst',
						options: {
							cacheName: 'gstatic-fonts-cache',
							expiration: {
								maxEntries: 10,
								maxAgeSeconds: 60 * 60 * 24 * 365 // 365 days
							},
							cacheableResponse: {
								statuses: [0, 200]
							}
						}
					}
				]
			},
			manifest: {
				name: 'Journey to Mordor',
				short_name: 'Journey to Mordor',
				description: 'Track your distance and journey to Mordor with Frodo',
				theme_color: '#1a1a1a',
				background_color: '#1a1a1a',
				display: 'standalone',
				icons: [
					{
						src: 'icon-192.png',
						sizes: '192x192',
						type: 'image/png'
					},
					{
						src: 'icon-512.png',
						sizes: '512x512',
						type: 'image/png'
					},
					{
						src: 'icon-512.png',
						sizes: '512x512',
						type: 'image/png',
						purpose: 'maskable'
					}
				]
			}
		})
	],

	build: {
		// Enable persistent caching for faster rebuilds
		// This caches processed images and other build artifacts
		rollupOptions: {
			cache: true
		}
	},

	// Enable Vite's persistent cache for dependencies and transformations
	cacheDir: 'node_modules/.vite',

	test: {
		expect: { requireAssertions: true },

		projects: [
			{
				extends: './vite.config.ts',

				test: {
					name: 'server',
					environment: 'node',
					include: ['src/**/*.{test,spec}.{js,ts}'],
					exclude: ['src/**/*.svelte.{test,spec}.{js,ts}']
				}
			}
		]
	}
});
